"""Initial migration

Revision ID: 94ae61ca06e0
Revises: 
Create Date: 2025-06-22 23:15:27.831293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94ae61ca06e0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('firstname', sa.String(length=64), nullable=False),
    sa.Column('lastname', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('request_created', sa.DateTime(), nullable=True),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('customer_filename', sa.String(length=255), nullable=True),
    sa.Column('original_resolution', sa.String(length=32), nullable=True),
    sa.Column('original_filesize', sa.Integer(), nullable=True),
    sa.Column('resized_filename', sa.String(length=255), nullable=True),
    sa.Column('resized_resolution', sa.String(length=32), nullable=True),
    sa.Column('new_filesize', sa.Integer(), nullable=True),
    sa.Column('reduce_to_percent', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('failure_reason', sa.String(length=255), nullable=True),
    sa.Column('expiry', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('requests')
    op.drop_table('users')
    # ### end Alembic commands ###
